# Generated by Django 6.0 on 2026-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogpost_meta_description_blogpost_meta_title_faq'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='blog_published_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='developer',
            index=models.Index(fields=['slug'], name='developer_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='developer',
            index=models.Index(fields=['name'], name='developer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['city'], name='district_city_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='property_created_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='property_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'district'], name='property_location_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['developer'], name='property_dev_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['low_price'], name='property_price_idx'),
        ),
    ]
