# Generated by Django 6.0 on 2026-01-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogpost_blog_published_idx_blogpost_blog_slug_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
